WALKTHROUGH = [
  {"zone": "Twilight Strand", "quest": "A Dirty Job", "text": "ACT 1\nKill Hillock. Enter the town."},
  {"zone": "The Coast", "quest": "The Mercy Mission", "text": "Grab [WP]. Go to Mud Flats."},
  {"zone": "The Mud Flats", "quest": "Breaking Some Eggs", "text": "Collect 3x Rhoa Glyphs [Q]. Open the passage.\n(Optional) Tidal Island: Kill Hailrake for Flask."},
  {"zone": "Submerged Passage", "quest": "The Dweller of the Deep", "text": "Grab [WP].\n(Optional) Flooded Depths: Kill Crab for [SKILL]."},
  {"zone": "The Ledge", "text": "Grab [WP]. Go to The Climb."},
  {"zone": "The Climb", "text": "Grab [WP]. Go to Lower Prison."},
  {"zone": "The Lower Prison", "text": "Grab [WP]. Do [TRIAL 1/6]. Go to Upper Prison."},
  {"zone": "The Upper Prison", "text": "Kill Brutus. Go to Prisoner's Gate."},
  {"zone": "Prisoner's Gate", "text": "Grab [WP]. Go to Ship Graveyard."},
  {"zone": "The Ship Graveyard", "text": "Grab [WP]. Find Cave, get Allflame [Q], kill Fairgraves [SKILL]."},
  {"zone": "The Caverns", "text": "Grab [WP]. Kill Merveil. Go to Act 2."},
  {"zone": "The Southern Forest", "text": "ACT 2\nGo to town (Forest Encampment)."},
  {"zone": "The Old Fields", "text": "Find The Den, kill White Beast [SKILL]. Go to Crossroads."},
  {"zone": "The Crossroads", "text": "Grab [WP]. Go top-left to Chamber of Sins."},
  {"zone": "The Chamber of Sins Level 1", "text": "Grab [WP]. Go to Level 2."},
  {"zone": "The Chamber of Sins Level 2", "text": "Do [TRIAL 2/6]. Kill Fidelitas, take Baleful Gem [Q]. Go to Crypt."},
  {"zone": "The Crypt Level 1", "text": "Grab [WP]. Do [TRIAL 3/6]. Return to town, go to Riverways."},
  {"zone": "The Riverways", "text": "Grab [WP]. Follow paved road to Western Forest."},
  {"zone": "The Western Forest", "text": "Grab [WP]. Kill guards, open seal (Way Forward [SKILL]). Kill/Help Alira. Find Weaver's Chambers."},
  {"zone": "The Weaver's Chambers", "text": "Kill spider, take Maligaro's Spike [Q]. Go to Wetlands."},
  {"zone": "The Wetlands", "text": "Grab [WP]. Kill/Help Oak. Destroy Vaal Ruins seal."},
  {"zone": "The Vaal Ruins", "text": "Navigate to Northern Forest."},
  {"zone": "The Northern Forest", "text": "Grab [WP]. *Bandits check: Go to Broken Bridge to Kill/Help Kraityn.* Go to The Caverns."},
  {"zone": "The Caverns", "text": "Grab [WP]. Go to Ancient Pyramid, kill Vaal Oversoul."},
  {"zone": "The City of Sarn", "text": "ACT 3\nRescue Clarissa. Go to town."},
  {"zone": "The Slums", "text": "Find Crematorium."},
  {"zone": "The Crematorium", "text": "Grab [WP]. Do [TRIAL 4/6]. Kill Piety, take Bracelet [Q]. Get Keys in town, open Sewers."},
  {"zone": "The Sewers", "text": "Find 3x Platinum Busts [SKILL]. Go to Marketplace."},
  {"zone": "The Marketplace", "text": "Grab [WP]. Enter Catacombs for [TRIAL 5/6]. Go to Battlefront."},
  {"zone": "The Battlefront", "text": "Grab [WP]. Take Ribbon Spool [Q]. Go to Docks."},
  {"zone": "The Docks", "text": "Grab [WP]. Find Sulphite [Q]. Go to Solaris Temple."},
  {"zone": "The Solaris Temple Level 2", "text": "Grab [WP]. Give items to Dialla for Talc [Q]. Destroy Undying Blockage in Sewers."},
  {"zone": "The Ebony Barracks", "text": "Grab [WP]. Kill Gravicius. Go to Lunaris Temple."},
  {"zone": "The Lunaris Temple Level 2", "text": "Kill Piety. Take Tower Key [Q]. Go to Imperial Gardens."},
  {"zone": "The Imperial Gardens", "text": "Grab [WP]. Do [TRIAL 6/6]. Go to Sceptre of God.\n*Good time for Normal Lab.*"},
  {"zone": "The Sceptre of God", "text": "Climb up. Kill Dominus."},
  {"zone": "The Aqueduct", "text": "ACT 4\nGo to town (Highgate)."},
  {"zone": "The Dried Lake", "text": "Kill Voll, take Banner [Q]. Open Mines."},
  {"zone": "The Mines Level 2", "text": "Free Deshret's Spirit [SKILL]. Go to Crystal Veins."},
  {"zone": "The Crystal Veins", "text": "Grab [WP]. Talk to Dialla. Complete Kaom's Dream & Daresso's Dream."},
  {"zone": "Kaom's Stronghold", "text": "Grab [WP]. Kill Kaom, get Eye [Q]."},
  {"zone": "The Grand Arena", "text": "Grab [WP]. Kill Daresso, get Eye [Q]. Enter Belly of the Beast."},
  {"zone": "The Belly of the Beast Level 2", "text": "Kill Piety. Enter Harvest."},
  {"zone": "The Harvest", "text": "Grab [WP]. Kill Doedre, Maligaro, Shavronne."},
  {"zone": "The Black Core", "text": "Kill Malachai."},
  {"zone": "The Slave Pens", "text": "ACT 5\nKill Overseer. Enter town."},
  {"zone": "The Control Blocks", "text": "Find Miasmeter [SKILL]. Kill Justicar. Go to Templar Courts."},
  {"zone": "The Chamber of Innocence", "text": "Grab [WP]. Kill Avarius. Return to town."},
  {"zone": "The Ruined Square", "text": "Grab [WP]. \n(Optional) Reliquary: Find 3x Torments [SKILL]."},
  {"zone": "The Ossuary", "text": "Find Sign of Purity [Q]. Return to Square."},
  {"zone": "The Cathedral Rooftop", "text": "Go to Apex. Kill Kitava (-30% Resists)."},
  {"zone": "The Twilight Strand", "text": "ACT 6\nClear ALL monsters [SKILL]."},
  {"zone": "The Mud Flats", "text": "Kill Dishonored Queen, take Eye [Q]."},
  {"zone": "The Karui Fortress", "text": "Kill Tukohama. Go to The Ridge."},
  {"zone": "The Ridge", "text": "Grab [WP]. Go to Lower Prison."},
  {"zone": "The Lower Prison", "text": "Grab [WP]. Do [TRIAL 1/6 (Cruel)]. Climb Tower."},
  {"zone": "Shavronne's Tower", "text": "Kill Brutus & Shavronne. Go to Prisoner's Gate."},
  {"zone": "Prisoner's Gate", "text": "Grab [WP]. Open Valley, kill Abberath [SKILL]."},
  {"zone": "The Western Forest", "text": "Grab [WP]. Follow road to Riverways."},
  {"zone": "The Riverways", "text": "Grab [WP]. Go to Wetlands."},
  {"zone": "The Wetlands", "text": "Kill Puppet Mistress [SKILL]. Return to Riverways, find Southern Forest."},
  {"zone": "The Cavern of Anger", "text": "Grab [WP]. Take Black Flag. Open passage."},
  {"zone": "The Beacon", "text": "Escort beacons, light them, talk to Weylam."},
  {"zone": "The Brine King's Reef", "text": "Kill Brine King."},
  {"zone": "The Broken Bridge", "text": "ACT 7\nFollow road to Crossroads."},
  {"zone": "The Crossroads", "text": "Grab [WP]. Go down to Fellshrine Ruins -> The Crypt."},
  {"zone": "The Crypt", "text": "Grab [WP]. Do [TRIAL 2/6 (Cruel)]. Find Maligaro's Map [Q]. Go to Chamber of Sins."},
  {"zone": "The Chamber of Sins Level 1", "text": "Grab [WP]. Use Map in Device. Kill Maligaro in Sanctum [Q]."},
  {"zone": "The Chamber of Sins Level 2", "text": "Do [TRIAL 3/6 (Cruel)]. Go to The Den -> Ashen Fields."},
  {"zone": "The Ashen Fields", "text": "Kill Greust [SKILL]. Go to Northern Forest."},
  {"zone": "The Northern Forest", "text": "Grab [WP]. Go to Dread Thicket."},
  {"zone": "The Dread Thicket", "text": "Collect 7x Fireflies [Q]. Kill Gruthkul [SKILL]."},
  {"zone": "The Causeway", "text": "Find Kishara's Star [SKILL]. Enter Vaal City."},
  {"zone": "The Vaal City", "text": "Grab [WP]. Light the fire. Enter Temple of Decay."},
  {"zone": "The Temple of Decay Level 2", "text": "Kill Arakaali (Spider)."},
  {"zone": "The Sarn Ramparts", "text": "ACT 8\nGo to Sarn Encampment."},
  {"zone": "Doedre's Cesspool", "text": "Kill Doedre. Fork in the road."},
  {"zone": "The Bath House", "text": "Left Path: Grab [WP]. Do [TRIAL 4/6 (Cruel)]. Go to High Gardens (Kill Yugul [SKILL]). Go to Lunaris Concourse."},
  {"zone": "The Lunaris Temple Level 2", "text": "Kill Dusk, take Sun Orb [Q]."},
  {"zone": "The Quay", "text": "Right Path: Find Ankh. Kill Tolman/save Clarissa [SKILL]."},
  {"zone": "The Grain Gate", "text": "Grab [WP]. Kill Gemling Legion [SKILL]."},
  {"zone": "The Solaris Temple Level 2", "text": "Grab [WP]. Kill Dawn, take Moon Orb [Q]."},
  {"zone": "The Harbour Bridge", "text": "Kill Solaris & Lunaris.\n*Good time for Cruel Lab.*"},
  {"zone": "The Blood Aqueduct", "text": "ACT 9\nGo to town (Highgate)."},
  {"zone": "The Vastiri Desert", "text": "Grab [WP]. Find Storm Blade [Q]. Get Bottled Storm in town, open Oasis. Kill Shakari [SKILL]."},
  {"zone": "The Foothills", "text": "Grab [WP]. Go to Boiling Lake."},
  {"zone": "The Boiling Lake", "text": "Kill Basilisk, take Acid [Q]. Return to Foothills, go to Tunnel."},
  {"zone": "The Tunnel", "text": "Grab [WP]. Do [TRIAL 5/6 (Cruel)]. Go to Quarry."},
  {"zone": "The Quarry", "text": "Grab [WP].\n1. Shrine of Winds: Kill Garukhan [SKILL].\n2. Refinery: Kill General, get Powder [Q]."},
  {"zone": "The Belly of the Beast", "text": "Enter from Quarry. Go to Rotting Core."},
  {"zone": "The Rotting Core", "text": "Kill Doedre, Maligaro, Shavronne. Kill Depraved Trinity."},
  {"zone": "Oriath Docks", "text": "ACT 10\nGo to Cathedral Rooftop, save Bannon."},
  {"zone": "The Ravaged Square", "text": "Grab [WP].\nControl Blocks: Kill Vilenta [SKILL]."},
  {"zone": "The Ossuary", "text": "Do [TRIAL 6/6 (Cruel)]. Return to Square."},
  {"zone": "The Desecrated Chambers", "text": "Grab [WP]. Kill Avarius. Take Staff [Q]. Give to Bannon."},
  {"zone": "The Canals", "text": "Follow Innocence to Feeding Trough."},
  {"zone": "The Feeding Trough", "text": "*DO MERCILESS LAB NOW!*\nKill Kitava. Claim 2x [SKILL] in Epilogue."}
]

TOWNS = {
    "Lioneye's Watch",
    "Forest Encampment",
    "The Forest Encampment",
    "Sarn Encampment",
    "The Sarn Encampment",
    "Highgate",
    "Overseer's Tower",
    "The Bridge Encampment",
    "Oriath Docks",
    "Karui Shores"
}
