import os

# Mapping of keywords/phrases to icon file paths
# Icon files are expected to be in the 'assets/icons' directory relative to the main application script.
ICON_MAPPING = {
    "WAYPOINT": "assets/icons/waypoint.png",
    "QUEST_ITEM": "assets/icons/quest_item.png",
    "SKILL_POINT": "assets/icons/skill_point.png",
    "TRIAL": "assets/icons/trial.png",
    "KILL_BOSS": "assets/icons/kill_boss.png",
    "ENTER_TOWN": "assets/icons/town.png",
    "ENTER_ZONE": "assets/icons/zone.png",
    "TAKE_REWARD": "assets/icons/reward.png",
    "OPEN_PASSAGE": "assets/icons/passage.png",
    "COLLECT_ITEM": "assets/icons/collect.png",
}

WALKTHROUGH = [
  {"zone": "Twilight Strand", "quest": "A Dirty Job", "text": "ACT 1\n[ICON:KILL_BOSS]Kill Hillock. [ICON:ENTER_TOWN]Enter the town."},
  {"zone": "The Coast", "quest": "The Mercy Mission", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Mud Flats."},
  {"zone": "The Mud Flats", "quest": "Breaking Some Eggs", "text": "[ICON:COLLECT_ITEM]Collect 3x Rhoa Glyphs [Q]. [ICON:OPEN_PASSAGE]Open the passage.\n(Optional) Tidal Island: [ICON:KILL_BOSS]Kill Hailrake for Flask."},
  {"zone": "Submerged Passage", "quest": "The Dweller of the Deep", "text": "[ICON:WAYPOINT]Grab [WP].\n(Optional) Flooded Depths: [ICON:KILL_BOSS]Kill Crab for [SKILL_POINT]."},
  {"zone": "The Ledge", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to The Climb."},
  {"zone": "The Climb", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Lower Prison."},
  {"zone": "The Lower Prison", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Do [TRIAL 1/6]. [ICON:ENTER_ZONE]Go to Upper Prison."},
  {"zone": "The Upper Prison", "text": "[ICON:KILL_BOSS]Kill Brutus. [ICON:ENTER_ZONE]Go to Prisoner's Gate."},
  {"zone": "Prisoner's Gate", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Ship Graveyard."},
  {"zone": "The Ship Graveyard", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Find Cave. [ICON:COLLECT_ITEM]Get Allflame [Q]. [ICON:KILL_BOSS]Kill Fairgraves [SKILL_POINT]."},
  {"zone": "The Caverns", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Merveil. [ICON:ENTER_ZONE]Go to Act 2."},
  {"zone": "The Southern Forest", "text": "ACT 2\n[ICON:ENTER_TOWN]Go to town (Forest Encampment)."},
  {"zone": "The Old Fields", "text": "[ICON:ENTER_ZONE]Find The Den. [ICON:KILL_BOSS]Kill White Beast [SKILL_POINT]. [ICON:ENTER_ZONE]Go to Crossroads."},
  {"zone": "The Crossroads", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go top-left to Chamber of Sins."},
  {"zone": "The Chamber of Sins Level 1", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Level 2."},
  {"zone": "The Chamber of Sins Level 2", "quest": "The Sharp and Cruel", "text": "[ICON:TRIAL]Do [TRIAL 2/6]. [ICON:KILL_BOSS]Kill Fidelitas. [ICON:COLLECT_ITEM]Take Baleful Gem [Q]. [ICON:ENTER_ZONE]Go to Crypt."},
  {"zone": "The Crypt Level 1", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Do [TRIAL 3/6]. [ICON:ENTER_TOWN]Return to town. [ICON:ENTER_ZONE]Go to Riverways."},
  {"zone": "The Riverways", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Follow paved road to Western Forest."},
  {"zone": "The Western Forest", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill guards. [ICON:OPEN_PASSAGE]Open seal (Way Forward [SKILL_POINT]). [ICON:KILL_BOSS]Kill/Help Alira. [ICON:ENTER_ZONE]Find Weaver's Chambers."},
  {"zone": "The Weaver's Chambers", "text": "[ICON:KILL_BOSS]Kill spider. [ICON:COLLECT_ITEM]Take Maligaro's Spike [Q]. [ICON:ENTER_ZONE]Go to Wetlands."},
  {"zone": "The Wetlands", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill/Help Oak. [ICON:OPEN_PASSAGE]Destroy Vaal Ruins seal."},
  {"zone": "The Vaal Ruins", "text": "[ICON:ENTER_ZONE]Navigate to Northern Forest."},
  {"zone": "The Northern Forest", "text": "[ICON:WAYPOINT]Grab [WP]. *Bandits check: [ICON:ENTER_ZONE]Go to Broken Bridge to [ICON:KILL_BOSS]Kill/Help Kraityn.* [ICON:ENTER_ZONE]Go to The Caverns."},
  {"zone": "The Caverns", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Ancient Pyramid. [ICON:KILL_BOSS]Kill Vaal Oversoul."},
  {"zone": "The City of Sarn", "quest": "Lost in Love", "text": "ACT 3\n[ICON:TAKE_REWARD]Rescue Clarissa. [ICON:ENTER_TOWN]Go to town."},
  {"zone": "The Slums", "text": "[ICON:ENTER_ZONE]Find Crematorium."},
  {"zone": "The Crematorium", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Do [TRIAL 4/6]. [ICON:KILL_BOSS]Kill Piety. [ICON:COLLECT_ITEM]Take Bracelet [Q]. [ICON:TAKE_REWARD]Get Keys in town. [ICON:OPEN_PASSAGE]Open Sewers."},
  {"zone": "The Sewers", "text": "[ICON:COLLECT_ITEM]Find 3x Platinum Busts [SKILL_POINT]. [ICON:ENTER_ZONE]Go to Marketplace."},
  {"zone": "The Marketplace", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Enter Catacombs for [TRIAL 5/6]. [ICON:ENTER_ZONE]Go to Battlefront."},
  {"zone": "The Battlefront", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:COLLECT_ITEM]Take Ribbon Spool [Q]. [ICON:ENTER_ZONE]Go to Docks."},
  {"zone": "The Docks", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:COLLECT_ITEM]Find Sulphite [Q]. [ICON:ENTER_ZONE]Go to Solaris Temple."},
  {"zone": "The Solaris Temple Level 2", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TAKE_REWARD]Give items to Dialla for Talc [Q]. [ICON:OPEN_PASSAGE]Destroy Undying Blockage in Sewers."},
  {"zone": "The Ebony Barracks", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Gravicius. [ICON:ENTER_ZONE]Go to Lunaris Temple."},
  {"zone": "The Lunaris Temple Level 2", "text": "[ICON:KILL_BOSS]Kill Piety. [ICON:COLLECT_ITEM]Take Tower Key [Q]. [ICON:ENTER_ZONE]Go to Imperial Gardens."},
  {"zone": "The Imperial Gardens", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Do [TRIAL 6/6]. [ICON:ENTER_ZONE]Go to Sceptre of God.\n*Good time for Normal Lab.*"},
  {"zone": "The Sceptre of God", "text": "[ICON:OPEN_PASSAGE]Climb up. [ICON:KILL_BOSS]Kill Dominus."},
  {"zone": "The Aqueduct", "text": "ACT 4\n[ICON:ENTER_TOWN]Go to town (Highgate)."},
  {"zone": "The Dried Lake", "text": "[ICON:KILL_BOSS]Kill Voll. [ICON:COLLECT_ITEM]Take Banner [Q]. [ICON:OPEN_PASSAGE]Open Mines."},
  {"zone": "The Mines Level 2", "text": "[ICON:TAKE_REWARD]Free Deshret's Spirit [SKILL_POINT]. [ICON:ENTER_ZONE]Go to Crystal Veins."},
  {"zone": "The Crystal Veins", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TAKE_REWARD]Talk to Dialla. [ICON:OPEN_PASSAGE]Complete Kaom's Dream & Daresso's Dream."},
  {"zone": "Kaom's Stronghold", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Kaom. [ICON:COLLECT_ITEM]Get Eye [Q]."},
  {"zone": "The Grand Arena", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Daresso. [ICON:COLLECT_ITEM]Get Eye [Q]. [ICON:ENTER_ZONE]Enter Belly of the Beast."},
  {"zone": "The Belly of the Beast Level 2", "text": "[ICON:KILL_BOSS]Kill Piety. [ICON:ENTER_ZONE]Enter Harvest."},
  {"zone": "The Harvest", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Doedre, Maligaro, Shavronne."},
  {"zone": "The Black Core", "text": "[ICON:KILL_BOSS]Kill Malachai."},
  {"zone": "The Slave Pens", "text": "ACT 5\n[ICON:KILL_BOSS]Kill Overseer. [ICON:ENTER_TOWN]Enter town."},
  {"zone": "The Control Blocks", "text": "[ICON:COLLECT_ITEM]Find Miasmeter [SKILL_POINT]. [ICON:KILL_BOSS]Kill Justicar. [ICON:ENTER_ZONE]Go to Templar Courts."},
  {"zone": "The Chamber of Innocence", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Avarius. [ICON:ENTER_TOWN]Return to town."},
  {"zone": "The Ruined Square", "text": "[ICON:WAYPOINT]Grab [WP]. \n(Optional) Reliquary: [ICON:COLLECT_ITEM]Find 3x Torments [SKILL_POINT]."},
  {"zone": "The Ossuary", "text": "[ICON:COLLECT_ITEM]Find Sign of Purity [Q]. [ICON:ENTER_ZONE]Return to Square."},
  {"zone": "The Cathedral Rooftop", "text": "[ICON:ENTER_ZONE]Go to Apex. [ICON:KILL_BOSS]Kill Kitava (-30% Resists)."},
  {"zone": "The Twilight Strand", "text": "ACT 6\n[ICON:KILL_BOSS]Clear ALL monsters [SKILL_POINT]."},
  {"zone": "The Mud Flats", "text": "[ICON:KILL_BOSS]Kill Dishonored Queen. [ICON:COLLECT_ITEM]Take Eye [Q]."},
  {"zone": "The Karui Fortress", "text": "[ICON:KILL_BOSS]Kill Tukohama. [ICON:ENTER_ZONE]Go to The Ridge."},
  {"zone": "The Ridge", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Lower Prison."},
  {"zone": "The Lower Prison", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Do [TRIAL 1/6 (Cruel)]. [ICON:OPEN_PASSAGE]Climb Tower."},
  {"zone": "Shavronne's Tower", "text": "[ICON:KILL_BOSS]Kill Brutus & Shavronne. [ICON:ENTER_ZONE]Go to Prisoner's Gate."},
  {"zone": "Prisoner's Gate", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:OPEN_PASSAGE]Open Valley. [ICON:KILL_BOSS]Kill Abberath [SKILL_POINT]."},
  {"zone": "The Western Forest", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Follow road to Riverways."},
  {"zone": "The Riverways", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Wetlands."},
  {"zone": "The Wetlands", "text": "[ICON:KILL_BOSS]Kill Puppet Mistress [SKILL_POINT]. [ICON:ENTER_ZONE]Return to Riverways. [ICON:ENTER_ZONE]Find Southern Forest."},
  {"zone": "The Cavern of Anger", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:COLLECT_ITEM]Take Black Flag. [ICON:OPEN_PASSAGE]Open passage."},
  {"zone": "The Beacon", "text": "[ICON:TAKE_REWARD]Escort beacons, light them. [ICON:TAKE_REWARD]Talk to Weylam."},
  {"zone": "The Brine King's Reef", "text": "[ICON:KILL_BOSS]Kill Brine King."},
  {"zone": "The Broken Bridge", "text": "ACT 7\n[ICON:ENTER_ZONE]Follow road to Crossroads."},
  {"zone": "The Crossroads", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go down to Fellshrine Ruins -> The Crypt."},
  {"zone": "The Crypt", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Do [TRIAL 2/6 (Cruel)]. [ICON:COLLECT_ITEM]Find Maligaro's Map [Q]. [ICON:ENTER_ZONE]Go to Chamber of Sins."},
  {"zone": "The Chamber of Sins Level 1", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:OPEN_PASSAGE]Use Map in Device. [ICON:KILL_BOSS]Kill Maligaro in Sanctum [Q]."},
  {"zone": "The Chamber of Sins Level 2", "text": "[ICON:TRIAL]Do [TRIAL 3/6 (Cruel)]. [ICON:ENTER_ZONE]Go to The Den -> Ashen Fields."},
  {"zone": "The Ashen Fields", "text": "[ICON:KILL_BOSS]Kill Greust [SKILL_POINT]. [ICON:ENTER_ZONE]Go to Northern Forest."},
  {"zone": "The Northern Forest", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Dread Thicket."},
  {"zone": "The Dread Thicket", "text": "[ICON:COLLECT_ITEM]Collect 7x Fireflies [Q]. [ICON:KILL_BOSS]Kill Gruthkul [SKILL_POINT]."},
  {"zone": "The Causeway", "text": "[ICON:COLLECT_ITEM]Find Kishara's Star [SKILL_POINT]. [ICON:ENTER_ZONE]Enter Vaal City."},
  {"zone": "The Vaal City", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:OPEN_PASSAGE]Light the fire. [ICON:ENTER_ZONE]Enter Temple of Decay."},
  {"zone": "The Temple of Decay Level 2", "text": "[ICON:KILL_BOSS]Kill Arakaali (Spider)."},
  {"zone": "The Sarn Ramparts", "text": "ACT 8\n[ICON:ENTER_TOWN]Go to Sarn Encampment."},
  {"zone": "Doedre's Cesspool", "text": "[ICON:KILL_BOSS]Kill Doedre. [ICON:OPEN_PASSAGE]Fork in the road."},
  {"zone": "The Bath House", "text": "Left Path: [ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Do [TRIAL 4/6 (Cruel)]. [ICON:ENTER_ZONE]Go to High Gardens ([ICON:KILL_BOSS]Kill Yugul [SKILL_POINT]). [ICON:ENTER_ZONE]Go to Lunaris Concourse."},
  {"zone": "The Lunaris Temple Level 2", "text": "[ICON:KILL_BOSS]Kill Dusk. [ICON:COLLECT_ITEM]Take Sun Orb [Q]."},
  {"zone": "The Quay", "text": "Right Path: [ICON:COLLECT_ITEM]Find Ankh. [ICON:KILL_BOSS]Kill Tolman/save Clarissa [SKILL_POINT]."},
  {"zone": "The Grain Gate", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Gemling Legion [SKILL_POINT]."},
  {"zone": "The Solaris Temple Level 2", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Dawn. [ICON:COLLECT_ITEM]Take Moon Orb [Q]."},
  {"zone": "The Harbour Bridge", "text": "[ICON:KILL_BOSS]Kill Solaris & Lunaris.\n*Good time for Cruel Lab.*"},
  {"zone": "The Blood Aqueduct", "text": "ACT 9\n[ICON:ENTER_TOWN]Go to town (Highgate)."},
  {"zone": "The Vastiri Desert", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:COLLECT_ITEM]Find Storm Blade [Q]. [ICON:TAKE_REWARD]Get Bottled Storm in town. [ICON:OPEN_PASSAGE]Open Oasis. [ICON:KILL_BOSS]Kill Shakari [SKILL_POINT]."},
  {"zone": "The Foothills", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:ENTER_ZONE]Go to Boiling Lake."},
  {"zone": "The Boiling Lake", "text": "[ICON:KILL_BOSS]Kill Basilisk. [ICON:COLLECT_ITEM]Take Acid [Q]. [ICON:ENTER_TOWN]Return to Foothills. [ICON:ENTER_ZONE]Go to Tunnel."},
  {"zone": "The Tunnel", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:TRIAL]Do [TRIAL 5/6 (Cruel)]. [ICON:ENTER_ZONE]Go to Quarry."},
  {"zone": "The Quarry", "text": "[ICON:WAYPOINT]Grab [WP].\n1. Shrine of Winds: [ICON:KILL_BOSS]Kill Garukhan [SKILL_POINT].\n2. Refinery: [ICON:KILL_BOSS]Kill General. [ICON:COLLECT_ITEM]Get Powder [Q]."},
  {"zone": "The Belly of the Beast", "text": "[ICON:ENTER_ZONE]Enter from Quarry. [ICON:ENTER_ZONE]Go to Rotting Core."},
  {"zone": "The Rotting Core", "text": "[ICON:KILL_BOSS]Kill Doedre, Maligaro, Shavronne. [ICON:KILL_BOSS]Kill Depraved Trinity."},
  {"zone": "Oriath Docks", "text": "ACT 10\n[ICON:ENTER_ZONE]Go to Cathedral Rooftop. [ICON:TAKE_REWARD]Save Bannon."},
  {"zone": "The Ravaged Square", "text": "[ICON:WAYPOINT]Grab [WP].\nControl Blocks: [ICON:KILL_BOSS]Kill Vilenta [SKILL_POINT]."},
  {"zone": "The Ossuary", "text": "[ICON:TRIAL]Do [TRIAL 6/6 (Cruel)]. [ICON:ENTER_ZONE]Return to Square."},
  {"zone": "The Desecrated Chambers", "text": "[ICON:WAYPOINT]Grab [WP]. [ICON:KILL_BOSS]Kill Avarius. [ICON:COLLECT_ITEM]Take Staff [Q]. [ICON:TAKE_REWARD]Give to Bannon."},
  {"zone": "The Canals", "text": "[ICON:ENTER_ZONE]Follow Innocence to Feeding Trough."},
  {"zone": "The Feeding Trough", "text": "*DO MERCILESS LAB NOW!*\n[ICON:KILL_BOSS]Kill Kitava. [ICON:TAKE_REWARD]Claim 2x [SKILL_POINT] in Epilogue."}
]

TOWNS = {
    "Lioneye's Watch",
    "Forest Encampment",
    "The Forest Encampment",
    "Sarn Encampment",
    "The Sarn Encampment",
    "Highgate",
    "Overseer's Tower",
    "The Bridge Encampment",
    "Oriath Docks",
    "Karui Shores"
}
